AWSTemplateFormatVersion: "2010-09-09"
Description: "TSRAIN Email Service"

Parameters:
    LatestAmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64'

    VpcId:
        Type: AWS::EC2::VPC::Id
        Description: The VPC ID
        AllowedPattern: "vpc-.+"

    InstanceType:
        Description: TSRAIN Email Service VM instance type
        Type: String
        Default: "t4g.nano"
        AllowedPattern: ".+"

    AllowIndividualPorts:
        Description: Enable access to individual Email Service ports
        Type: String
        AllowedValues:
            - true
            - false
        Default: false

Conditions:
    AllowIndividualPorts: !Equals [!Ref AllowIndividualPorts, false]

Resources:
    EC2:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !Ref LatestAmiId
            InstanceType: !Ref InstanceType
            NetworkInterfaces:
                - AssociatePublicIpAddress: "true"
                  DeviceIndex: "0"
                  GroupSet:
                    - !Ref SecurityGroupTsrainAws443
                    - !If
                        - AllowIndividualPorts
                        - !Ref SecurityGroupTsrainAwsIndividualPorts
                        - !Ref AWS::NoValue
            UserData:
                !Base64 |
                #!/bin/bash
                curl -s -L https://github.com/spearmin10/demo/blob/main/tsrain-installer/ec2-al2023/install.sh?raw=true | bash
            Tags:
                - Key: Name
                  Value: TSRAIN Email Service

    SecurityGroupTsrainAws443:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: tsrain-443
            GroupDescription: Run All Services on Port 443
            VpcId: !Ref VpcId
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 443
                  ToPort: 443
                  CidrIp: 0.0.0.0/0
                  Description: "Run All Services on Port 443"

    SecurityGroupTsrainAwsIndividualPorts:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: tsrain-individual-services
            GroupDescription: Individual email service ports
            VpcId: !Ref VpcId
            SecurityGroupIngress:
                # http
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
                  Description: "WebMail Frontend"
                # smtp
                - IpProtocol: tcp
                  FromPort: 25
                  ToPort: 25
                  CidrIp: 0.0.0.0/0
                  Description: "SMTP"
                # smtps
                - IpProtocol: tcp
                  FromPort: 465
                  ToPort: 465
                  CidrIp: 0.0.0.0/0
                  Description: "SMTP (SSL)"
                # imap
                - IpProtocol: tcp
                  FromPort: 143
                  ToPort: 143
                  CidrIp: 0.0.0.0/0
                  Description: "IMAP"
                # imaps
                - IpProtocol: tcp
                  FromPort: 993
                  ToPort: 993
                  CidrIp: 0.0.0.0/0
                  Description: "IMAP (SSL)"

Outputs:
    EC2PublicIP:
        Value: !GetAtt EC2.PublicIp
        Description: Public IP of EC2 instance
